language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  
before_install:
  - pecl install xdebug-2.5.5
  - phpenv rehash
  - wget https://scrutinizer-ci.com/ocular.phar

before_script:
  - composer selfupdate

script:
  - composer install
  - vendor/bin/robo build
  - php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/target/reports/unit/clover.xml

notifications:
  email: t.wagner@techdivision.com